apiVersion: v1
kind: Pod
metadata:
  name: appcolor
  labels:
    app: "web"
  namespace: "production"
spec:
  containers:
    - name: color
      image: mmumshad/simple-webapp-color:latest
      ports:
        - containerPort: 8080
      env:
        - name: APP_COLOR
          value: red
