apiVersion: v1 
kind: Service
metadata:
  name: nodeport
  namespace: "production"
spec:
  type: LoadBalancer  
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30001
 
