apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          #resources:
          # requests:
          #    memory: "150M"
          #    cpu: "500m"
          #  limits:
          #    memory: "250M"
          #    cpu: "500m"
          ports:
            - containerPort: 3306
              name: mysql
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-wp
                key: rootpwd
      volumes:
        - name: mysql-pstorage
          persistentVolumeClaim:
            claimName: mysql-wp-vc
     
