apiVersion: v1
kind: Pod
metadata:
  name: pgsqlpod
  labels:
    app: "bdd"
    type: "pgsl"
spec:
  containers:
    - name: postgres
      image: postgres:10.4
      ports:
        - containerPort: 5432
      envFrom:
        - configMapRef:
            name: postgres-config
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pgsql-volume    
  volumes:
    - name: pgsql-volume
      hostPath:
        # directory location on host
        path: /tmp/data-volume
        # this field is optional
        type: DirectoryOrCreate
        
