apiVersion: v1
data:
  database: d29yZHByZXNz
  rootpwd: UGFzc3dvcmQ=
  user: cm9vdA==
  userpwd: VXNlclBhc3N3b3Jk
kind: Secret
metadata:
  creationTimestamp: "2021-10-19T18:22:39Z"
  name: mysql-wp
  namespace: default
  resourceVersion: "2921"
  uid: c1fb77ad-567d-4b92-b83f-e2f4dbea2993
type: Opaque
